### ISSUE TITLE
E-Mails needs to be rephrased in English

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/epi-lab-client#52]
Old: "you have registered for an Epi-Lab account. Use the button below to activate your account. This activation link is only valid for the next 24 hours.

Activate your account
For security, this request was received from a Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36 device using . If you did not register for an Epi-Lab account, please ignore this email or contact support if you have questions.

Thanks, 
The Epi-Lab Team"

Suggestion: "you have registered for an MIBI-PORTAL account. Use the LINK below to activate your account. This activation link is only valid for the next 24 hours.

Activate your account
For security, this request was received from a Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36 device using [?????]. If you did not register for an MIBI-PORTAL account, please ignore this email or contact [EMAIL ADRESS] if you have questions.

SINCERELY, 
The MIBI-PORTAL Team"

**Comment by dptolle** [comment]
Issue moved to [SiLeBAT/epi-lab-server #18](https://github.com/SiLeBAT/epi-lab-server/issues/18) via [**ZenHub**](https://www.zenhub.com/)

**Comment by dptolle** [comment]
Issue moved to [SiLeBAT/epi-lab-server #19](https://github.com/SiLeBAT/epi-lab-server/issues/19) via [**ZenHub**](https://www.zenhub.com/)
